### ISSUE TITLE
t/time_zone.t fails (without LWP::Simple::WithCache?)

### ISSUE THREAD

**Issue by eserte** [nigelhorne/CGI-Lingua#22]
The test suite fails on some of my smokers, possibly if LWP::Simple::WithCache is not installed:
```
You must have LWP::Simple::WithCache installed to connect to ip-api.com at t/time_zone.t line 40.
# Looks like your test exited with 2 just after 4.
t/time_zone.t ...... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 4/8 subtests 
```

**Comment by nigelhorne** [comment]
That's strange because the entire point of that test (t/rt131067.t - the message is wrong) is to purposely disable that module it if it is installed.  So not having that module is irrelevant.  I'm not saying that there isn't something amiss, I'm saying that isn't it.  It's almost as though, in your environment, it's dying in the eval, which shouldn't happen.

**Comment by eserte** [comment]
It's really time_zone.t which is failing, not rt131067.t. It seems to happen if Geo::IP is installed but LWP::Simple::WithCache is not.

**Comment by nigelhorne** [comment]
What is the output of

`ls -l /usr/local/share/GeoIP/GeoIP.dat`

**Comment by nigelhorne** [comment]
If that's not found, what is the output of

`locate GeoIP.dat`

**Comment by eserte** [comment]
`/usr/local/share/GeoIP/GeoIP.dat` does not exist on any of my smokers.
Three smokers have instead `/usr/share/GeoIP/GeoIP.dat`.
The others don't have `locate` installed.

**Comment by nigelhorne** [comment]
What happens when you try it against the latest commit (https://github.com/nigelhorne/CGI-Lingua/commit/64475dd4dd51978d18a03cb6082d319a45797ca8)?

**Comment by eserte** [comment]
The latest seems to be 8379f0aa834c95411be626a231fa375a19965293
I checked that one on one of my smokers, and it looks OK.

**Comment by nigelhorne** [comment]
Perfect - thank you for checking.
